"""
tests/test_analysis.py: unit tests for the probe statistics in analysis.py.

The central test is that the battery discriminates the three accounts the study
must tell apart, using synthetic logs generated from each:

  * `grounded`: the action follows the scene, and the term selects which target.
  * `lexical`: the term fixes the direction and the image plays no part.
  * `blind`: the output ignores instruction and image alike.

A `lexical` model reproduces the antonym sign flip perfectly, so it passes the
original sign-flip metric. Confirming that the controls separate it from
`grounded` is what justifies the rebuild, and a regression there would silently
restore the ambiguity the earlier design suffered from.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from analysis import (
    OBJECT_SIDE_LEFT,
    OBJECT_SIDE_RIGHT,
    TRACKING_CONDITION_MIRROR,
    TRACKING_CONDITION_ORIGINAL,
    absolute_congruence,
    axis_value,
    congruence_test,
    determinism_check,
    lexical_check,
    mirror_check,
    mirror_check_by_configuration,
    mirrored_x,
    object_side_image,
    object_tracking_by_axis,
    object_tracking_by_sign,
    apply_tracking_instruction,
    attach_tracking_ground_truth,
    object_tracking_candidates,
    object_tracking_gate,
    object_tracking_report,
    proportion_lower_bound,
    stale_tracking_prompt_count,
    tracking_gt_predictions,
    tracking_instruction,
    resolution_report,
    same_side_test,
    term_effect,
    tost_equivalence,
    toward_object,
    value_column,
    wilcoxon_paired,
)

BIN_WIDTH = 0.001118


def _row(scene_id, condition, role, value, axis_index=0, configuration="opposite",
         expected_sign_image=-1, target_sign_a_image=-1, target_sign_b_image=1,
         base_scene_id="f0", spatial_term="left"):
    row = {
        "scene_id": scene_id, "condition": condition, "role": role,
        "axis_index": axis_index, "configuration": configuration,
        "base_scene_id": base_scene_id, "spatial_term": spatial_term,
        "expected_sign_image": expected_sign_image,
        "target_sign_a_image": target_sign_a_image,
        "target_sign_b_image": target_sign_b_image,
        "instruction": f"{scene_id}-{role}-{condition}",
    }
    for i in range(7):
        row[f"c{i}"] = value if i == axis_index else 0.0
        row[f"a{i}"] = value if i == axis_index else 0.0
    return row


def synthetic_log(model, n=40, seed=0, scale=0.01):
    """A prediction log generated by one of the three accounts.

    Geometry is expressed the way the probe logs it: image coordinates in which a
    negative sign is further left in the frame, with role `a` always carrying the
    term `left`. Consecutive scenes share a base frame and take the two
    arrangements, matching the frozen evaluation set, so the paired form of the
    decisive contrast has something to pair.

    `scale` sets the magnitude of every prediction, which is what the magnitude
    floor is read against.
    """
    rng = np.random.default_rng(seed)
    rows = []
    for s in range(n):
        configuration = "opposite" if s % 2 == 0 else "same_side_left"
        # Where each instruction's target sits, relative to the start position.
        # In the same-side arrangement both lie in the same direction, which is
        # the condition that separates the grounded and lexical accounts, and it
        # is also the arrangement whose `right` instruction is incongruent with
        # the side its own target occupies.
        if configuration == "opposite":
            target_a, target_b = -1.0, 1.0
        else:
            target_a, target_b = -1.0, -0.4
        scene = f"s{s}"

        def value(role, target, mirrored=False, no_referent=False):
            if model == "grounded":
                # The term-free instruction still reaches for the object, which
                # is the object-grounding baseline the mirror control reads.
                base = target_a if role == "n" else target
                if no_referent:
                    base = rng.choice([-1.0, 1.0]) * 0.05
                return -base if mirrored else base
            if model == "lexical":
                # The word fixes the direction; the scene plays no part, so
                # mirroring changes nothing.
                return {"a": -1.0, "b": 1.0, "n": 0.0}[role]
            return 0.0

        def row(condition, role, val):
            return _row(scene, condition, role, val * scale,
                        configuration=configuration,
                        base_scene_id=f"f{s // 2}",
                        expected_sign_image=int(np.sign(target_a - target_b)),
                        target_sign_a_image=int(np.sign(target_a)),
                        target_sign_b_image=int(np.sign(target_b)))

        for role, target in (("a", target_a), ("b", target_b)):
            rows.append(row("baseline", role, value(role, target)))
            rows.append(row("swapped_scene", role,
                            value(role, target, no_referent=True)))
            rows.append(row("mirror", role, value(role, target, mirrored=True)))
        rows.append(row("neutral", "n", value("n", target_a)))
        rows.append(row("mirror_neutral", "n", value("n", target_a, mirrored=True)))
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------- #
# Axis selection
# --------------------------------------------------------------------------- #
def test_value_column_names_the_right_readout():
    assert value_column(0) == "c0" and value_column(1) == "c1"
    assert value_column(0, continuous=False) == "a0"


def test_axis_value_reads_each_row_on_its_own_axis():
    # Pooling a depth pair onto the lateral component is the bug this prevents.
    frame = pd.DataFrame([
        _row("lateral", "baseline", "a", 0.5, axis_index=0),
        _row("depth", "baseline", "a", 0.7, axis_index=1),
        _row("vertical", "baseline", "a", 0.9, axis_index=2),
    ])
    assert list(axis_value(frame)) == [0.5, 0.7, 0.9]


# --------------------------------------------------------------------------- #
# Paired tests
# --------------------------------------------------------------------------- #
def test_wilcoxon_reports_direction_and_size():
    result = wilcoxon_paired([0.1] * 10 + [0.05] * 10)
    assert result["n"] == 20
    assert result["median"] > 0
    assert result["p_value"] < 0.05
    assert result["rank_biserial"] == pytest.approx(1.0)


def test_wilcoxon_is_degenerate_safe():
    for values in ([], [0.0], [0.0] * 20):
        result = wilcoxon_paired(values)
        assert np.isnan(result["p_value"])
    assert wilcoxon_paired([0.0] * 20)["n_zero"] == 20


def test_wilcoxon_ignores_non_finite_values():
    assert wilcoxon_paired([0.1, np.nan, 0.2, np.inf])["n"] == 2


def test_tost_declares_a_tiny_effect_equivalent():
    rng = np.random.default_rng(0)
    tiny = rng.normal(0, BIN_WIDTH / 20, size=60)
    assert tost_equivalence(tiny, BIN_WIDTH)["equivalent"]


def test_tost_does_not_declare_a_large_effect_equivalent():
    rng = np.random.default_rng(0)
    large = rng.normal(10 * BIN_WIDTH, BIN_WIDTH, size=60)
    assert not tost_equivalence(large, BIN_WIDTH)["equivalent"]


def test_tost_handles_a_constant_sample():
    assert tost_equivalence([0.0] * 10, BIN_WIDTH)["equivalent"]
    assert not tost_equivalence([1.0] * 10, BIN_WIDTH)["equivalent"]


def test_tost_is_inconclusive_on_a_small_noisy_sample():
    # Neither different from zero nor demonstrably negligible.
    rng = np.random.default_rng(1)
    result = tost_equivalence(rng.normal(0, 5 * BIN_WIDTH, size=4), BIN_WIDTH)
    assert not result["equivalent"]


# --------------------------------------------------------------------------- #
# Resolution
# --------------------------------------------------------------------------- #
def test_resolution_report_exposes_a_floored_measurement():
    result = resolution_report([0.0] * 30, BIN_WIDTH)
    assert result["frac_exact_zero"] == 1.0
    assert result["n_distinct"] == 1


def test_resolution_report_counts_sub_bin_differences():
    values = [BIN_WIDTH / 4] * 10 + [BIN_WIDTH * 5] * 10
    result = resolution_report(values, BIN_WIDTH)
    assert result["frac_below_bin"] == pytest.approx(0.5)
    assert result["frac_exact_zero"] == 0.0


def test_resolution_report_handles_empty_input():
    assert resolution_report([], BIN_WIDTH)["n"] == 0


# --------------------------------------------------------------------------- #
# Discrimination between the three accounts
# --------------------------------------------------------------------------- #
def test_mirror_check_separates_a_live_visual_channel_from_a_dead_one():
    grounded = mirror_check(synthetic_log("grounded"))
    lexical = mirror_check(synthetic_log("lexical"))
    assert grounded["neutral"]["flip_rate"] == pytest.approx(1.0)
    assert grounded["neutral"]["antisymmetry"]["median"] == pytest.approx(0.0)
    # The lexical model's output does not move when the scene is reflected.
    assert lexical["term"]["flip_rate"] == pytest.approx(0.0)
    assert lexical["term"]["invariance"]["median"] == pytest.approx(0.0)


def test_lexical_check_detects_a_contrast_that_survives_without_its_scene():
    grounded = lexical_check(synthetic_log("grounded"))
    lexical = lexical_check(synthetic_log("lexical"))
    assert grounded["ratio"] < 0.2
    assert lexical["ratio"] == pytest.approx(1.0)


def test_mirror_check_is_reported_per_arrangement():
    """The arrangements are not equally informative, so they are not pooled.

    Reflecting an `opposite` scene maps the layout onto itself, so the check can
    only detect a live visual channel on the same-side arrangements.
    """
    per_config = mirror_check_by_configuration(synthetic_log("grounded"))
    assert set(per_config) == {"opposite", "same_side_left"}
    assert per_config["same_side_left"]["neutral"]["flip_rate"] == pytest.approx(1.0)


def test_same_side_test_is_the_decisive_contrast():
    grounded = same_side_test(synthetic_log("grounded"))
    lexical = same_side_test(synthetic_log("lexical"))
    # Both accounts behave identically on the opposite configuration, which is
    # exactly why that arrangement alone cannot decide between them.
    assert grounded["by_configuration"]["opposite"]["same_sign_rate"] == pytest.approx(0.0)
    assert lexical["by_configuration"]["opposite"]["same_sign_rate"] == pytest.approx(0.0)
    # They diverge completely on the same-side configuration.
    assert grounded["by_configuration"]["same_side_left"]["same_sign_rate"] == pytest.approx(1.0)
    assert lexical["by_configuration"]["same_side_left"]["same_sign_rate"] == pytest.approx(0.0)
    assert grounded["contrast"]["difference"] == pytest.approx(1.0)
    assert grounded["contrast"]["p_value"] < 0.01
    assert lexical["contrast"]["difference"] == pytest.approx(0.0)


def test_the_decisive_contrast_is_paired_within_the_base_frame():
    """The frozen set builds both arrangements from one frame, so the contrast
    can hold the frame fixed instead of comparing two groups of scenes."""
    grounded = same_side_test(synthetic_log("grounded"))["contrast_paired"]
    lexical = same_side_test(synthetic_log("lexical"))["contrast_paired"]
    assert grounded["n_pairs"] == 20 and grounded["n_unpaired"] == 0
    assert grounded["difference"] == pytest.approx(1.0)
    assert grounded["n_discordant"] == 20 and grounded["only_same_side"] == 20
    assert grounded["p_value"] < 0.01
    # The lexical account behaves the same way in both arrangements, so every
    # pair is concordant and there is nothing for the test to reject.
    assert lexical["n_discordant"] == 0
    assert np.isnan(lexical["p_value"])


def test_the_paired_contrast_reports_when_no_pairing_was_logged():
    log = synthetic_log("grounded").drop(columns=["base_scene_id"])
    paired = same_side_test(log)["contrast_paired"]
    assert paired["n_pairs"] == 0
    assert "base_scene_id" in paired["note"]


def test_sign_based_rates_can_be_held_to_one_action_bin():
    """A sign below the quantisation floor is not a decision the model executes.

    Every prediction here is a tenth of a bin, so with the floor applied nothing
    is scored and the scenes are counted as undecided rather than contributing an
    arbitrary sign.
    """
    tiny = synthetic_log("grounded", scale=BIN_WIDTH / 10)
    assert same_side_test(tiny)["by_configuration"]["same_side_left"]["n"] > 0
    floored = same_side_test(tiny, min_magnitude=BIN_WIDTH)
    assert floored["by_configuration"]["same_side_left"]["n"] == 0
    assert absolute_congruence(tiny, min_magnitude=BIN_WIDTH)["n"] == 0
    assert absolute_congruence(tiny, min_magnitude=BIN_WIDTH)["n_unresolved"] == 40
    # The same predictions an order of magnitude above the bin are kept.
    large = synthetic_log("grounded", scale=BIN_WIDTH * 10)
    assert absolute_congruence(large, min_magnitude=BIN_WIDTH)["n"] == 40


def test_congruence_on_the_difference_cannot_separate_the_accounts():
    # Both accounts orient the paired difference the same way, because the
    # term's conventional direction and the recorded order of the two targets
    # coincide by construction. This is the limitation that makes the paired
    # difference, and the original sign-flip metric built on it, insufficient
    # on its own; absolute_congruence is the statistic that discriminates.
    assert congruence_test(synthetic_log("grounded"))["agreement"] == pytest.approx(1.0)
    assert congruence_test(synthetic_log("lexical"))["agreement"] == pytest.approx(1.0)


def test_absolute_congruence_separates_the_accounts_on_same_side_scenes():
    grounded = absolute_congruence(synthetic_log("grounded"))["by_configuration"]
    lexical = absolute_congruence(synthetic_log("lexical"))["by_configuration"]
    # Both targets share a side, so a fixed word-to-direction mapping can only
    # ever point at one of them.
    assert grounded["same_side_left"]["agreement"] == pytest.approx(1.0)
    assert lexical["same_side_left"]["agreement"] == pytest.approx(0.5)
    assert grounded["same_side_left"]["both_correct"] == pytest.approx(1.0)
    assert lexical["same_side_left"]["both_correct"] == pytest.approx(0.0)
    # The opposite arrangement cannot tell them apart, which is why the rate is
    # reported per configuration rather than pooled.
    assert grounded["opposite"]["agreement"] == pytest.approx(1.0)
    assert lexical["opposite"]["agreement"] == pytest.approx(1.0)


def test_absolute_congruence_pools_the_decisive_instructions_by_congruency():
    """Where the accounts part is the instruction whose term names the other side.

    Both accounts agree on the congruent instruction, so pooling the incongruent
    ones across arrangements isolates the discrimination and doubles the sample
    for it.
    """
    grounded = absolute_congruence(synthetic_log("grounded"))["by_congruency"]
    lexical = absolute_congruence(synthetic_log("lexical"))["by_congruency"]
    assert grounded["congruent"]["agreement"] == pytest.approx(1.0)
    assert grounded["incongruent"]["agreement"] == pytest.approx(1.0)
    assert lexical["congruent"]["agreement"] == pytest.approx(1.0)
    assert lexical["incongruent"]["agreement"] == pytest.approx(0.0)
    # Only the same-side arrangement produces an incongruent instruction, and it
    # produces exactly one per scene.
    assert grounded["incongruent"]["n"] == 20
    assert set(grounded["incongruent"]["by_configuration"]) == {"same_side_left"}


def test_the_sign_convention_is_applied_at_analysis_time():
    """Inverting the convention inverts agreement, and names the third reading.

    A rate near zero is the grounded account under an inverted convention, not a
    separate account, which is why the convention is a parameter here rather than
    a constant baked into the log.
    """
    log = synthetic_log("grounded")
    assert absolute_congruence(log, lateral_sign=1)["agreement"] == pytest.approx(1.0)
    assert absolute_congruence(log, lateral_sign=-1)["agreement"] == pytest.approx(0.0)
    assert congruence_test(log, lateral_sign=-1)["agreement"] == pytest.approx(0.0)


def test_the_mirrored_stimulus_replicates_the_decisive_test():
    """Reflection negates the recorded geometry, giving a second measurement.

    The grounded account tracks the reflected layout, so it agrees again once the
    geometry is negated. The lexical account cannot, because its output did not
    move when the scene did.
    """
    grounded = absolute_congruence(synthetic_log("grounded"), condition="mirror",
                                   geometry_sign=-1)
    lexical = absolute_congruence(synthetic_log("lexical"), condition="mirror",
                                 geometry_sign=-1)
    assert grounded["by_configuration"]["same_side_left"]["agreement"] == pytest.approx(1.0)
    assert lexical["by_configuration"]["same_side_left"]["agreement"] == pytest.approx(0.5)
    # The same-sign statistic needs no convention at all, so it replicates as is.
    mirrored = same_side_test(synthetic_log("grounded"), condition="mirror")
    assert mirrored["by_configuration"]["same_side_left"]["same_sign_rate"] == pytest.approx(1.0)


def test_absolute_congruence_reports_when_the_target_sides_were_not_logged():
    log = synthetic_log("grounded").drop(
        columns=["target_sign_a_image", "target_sign_b_image"])
    assert absolute_congruence(log)["n"] == 0


def test_term_effect_finds_opposed_deviations_only_where_the_term_acts():
    lexical = term_effect(synthetic_log("lexical"))
    blind = term_effect(synthetic_log("blind"))
    assert lexical["opposed_rate"] == pytest.approx(1.0)
    assert blind["both_zero_rate"] == pytest.approx(1.0)


def test_a_blind_model_produces_a_null_everywhere():
    log = synthetic_log("blind")
    assert same_side_test(log)["by_configuration"]["opposite"]["n"] == 0
    assert term_effect(log)["opposed_rate"] == pytest.approx(0.0)
    diffs = np.zeros(20)
    assert tost_equivalence(diffs, BIN_WIDTH)["equivalent"]


def test_statistics_are_empty_safe():
    empty = pd.DataFrame(columns=["scene_id", "condition", "role", "axis_index",
                                  "configuration", "base_scene_id", "instruction",
                                  "spatial_term", "expected_sign_image",
                                  "target_sign_a_image", "target_sign_b_image",
                                  *[f"c{i}" for i in range(7)],
                                  *[f"a{i}" for i in range(7)]])
    assert mirror_check(empty)["term"]["n"] == 0
    assert mirror_check_by_configuration(empty) == {}
    assert term_effect(empty)["n"] == 0
    assert congruence_test(empty)["n"] == 0
    assert same_side_test(empty)["n"] == 0
    assert absolute_congruence(empty)["n"] == 0
    assert determinism_check(empty)["deterministic"]
    assert object_tracking_report(empty, empty)["n"] == 0


# --------------------------------------------------------------------------- #
# Determinism
# --------------------------------------------------------------------------- #
def test_determinism_check_passes_on_identical_repeats():
    log = synthetic_log("grounded", n=5)
    doubled = pd.concat([log, log], ignore_index=True)
    assert determinism_check(doubled)["deterministic"]


def test_determinism_check_catches_a_disagreeing_repeat():
    log = synthetic_log("grounded", n=5)
    drifted = log.copy()
    drifted.loc[drifted.index[0], "c0"] += 1e-6
    doubled = pd.concat([log, drifted], ignore_index=True)
    result = determinism_check(doubled)
    assert not result["deterministic"]
    assert result["max_spread"] > 0


# --------------------------------------------------------------------------- #
# First-action object tracking
# --------------------------------------------------------------------------- #
GRIPPER_X = 320.0
FRAME_WIDTH = 640.0
OBJECT_LEFT_X = 200.0
OBJECT_RIGHT_X = 440.0


def _track_pred(scene_id, condition, values):
    """One tracking-log row. `values` is a 3-tuple (dx, dy, dz)."""
    row = {
        "scene_id": scene_id, "condition": condition, "role": "n",
        "axis_index": 0,
    }
    padded = list(values) + [0.0] * (7 - len(values))
    for i in range(7):
        row[f"c{i}"] = padded[i]
        row[f"a{i}"] = padded[i]
    return row


def _track_geom(scene_id, x_object):
    return {
        "scene_id": scene_id,
        "x_object": x_object,
        "x_gripper": GRIPPER_X,
        "image_width": FRAME_WIDTH,
    }


def tracking_synthetic(model, n=40, scale=0.01):
    """Predictions and geometry for a unique-object tracking check.

    Half the objects sit left of the gripper, half right. `grounded` reaches
    for the object and reverses under a mirror. `image_left` always emits a
    negative lateral action, which agrees with the object only when the object
    is on the left and does not reverse. `blind` emits zero.
    """
    preds, geom = [], []
    for i in range(n):
        scene = f"t{i}"
        x_object = OBJECT_LEFT_X if i % 2 == 0 else OBJECT_RIGHT_X
        side = np.sign(x_object - GRIPPER_X)
        if model == "grounded":
            orig = side * scale
            mirrored_side = np.sign(
                mirrored_x(x_object, FRAME_WIDTH) - mirrored_x(GRIPPER_X, FRAME_WIDTH))
            mir = mirrored_side * scale
        elif model == "image_left":
            orig = mir = -scale
        else:
            orig = mir = 0.0
        preds.append(_track_pred(scene, TRACKING_CONDITION_ORIGINAL, (orig, 0.0, 0.0)))
        preds.append(_track_pred(scene, TRACKING_CONDITION_MIRROR, (mir, 0.0, 0.0)))
        geom.append(_track_geom(scene, x_object))
    return pd.DataFrame(preds), pd.DataFrame(geom)


def test_object_side_image_and_mirror_are_opposites():
    assert object_side_image(OBJECT_LEFT_X, GRIPPER_X) == -1
    assert object_side_image(OBJECT_RIGHT_X, GRIPPER_X) == 1
    assert object_side_image(GRIPPER_X, GRIPPER_X) == 0
    # A horizontal flip swaps the object's side of the gripper.
    assert object_side_image(
        mirrored_x(OBJECT_LEFT_X, FRAME_WIDTH),
        mirrored_x(GRIPPER_X, FRAME_WIDTH),
    ) == 1


def test_toward_object_follows_the_recorded_side():
    assert toward_object(-0.01, OBJECT_LEFT_X, GRIPPER_X) is True
    assert toward_object(0.01, OBJECT_LEFT_X, GRIPPER_X) is False
    assert toward_object(0.01, OBJECT_RIGHT_X, GRIPPER_X) is True
    assert toward_object(0.0, OBJECT_RIGHT_X, GRIPPER_X) is None
    assert toward_object(0.01, GRIPPER_X, GRIPPER_X) is None
    # Below one bin the sign is not a decision the model could execute.
    assert toward_object(0.0001, OBJECT_RIGHT_X, GRIPPER_X,
                         min_magnitude=0.001) is None


def test_toward_object_applies_the_sign_convention_at_read_time():
    assert toward_object(-0.01, OBJECT_LEFT_X, GRIPPER_X, lateral_sign=1) is True
    assert toward_object(-0.01, OBJECT_LEFT_X, GRIPPER_X, lateral_sign=-1) is False


def test_object_tracking_report_passes_only_for_a_tracker():
    grounded = object_tracking_report(*tracking_synthetic("grounded"))
    prior = object_tracking_report(*tracking_synthetic("image_left"))
    blind = object_tracking_report(*tracking_synthetic("blind"))

    assert grounded["n"] == 40
    assert grounded["toward_original"] == pytest.approx(1.0)
    assert grounded["toward_mirror"] == pytest.approx(1.0)
    assert grounded["flip_rate"] == pytest.approx(1.0)
    assert grounded["by_object_side"][OBJECT_SIDE_LEFT]["toward_original"] == pytest.approx(1.0)
    assert grounded["by_object_side"][OBJECT_SIDE_RIGHT]["toward_original"] == pytest.approx(1.0)

    # An image-left prior agrees only when the object happens to sit on the left
    # and does not reverse when the frame is mirrored.
    assert prior["by_object_side"][OBJECT_SIDE_LEFT]["toward_original"] == pytest.approx(1.0)
    assert prior["by_object_side"][OBJECT_SIDE_RIGHT]["toward_original"] == pytest.approx(0.0)
    assert prior["flip_rate"] == pytest.approx(0.0)
    assert prior["negative_rate_original"] == pytest.approx(1.0)
    assert prior["negative_rate_mirror"] == pytest.approx(1.0)

    assert blind["n"] == 40
    assert blind["n_undecided_original"] == 40
    assert np.isnan(blind["toward_original"])


def test_object_tracking_gate_rejects_an_image_left_prior():
    grounded = object_tracking_gate(object_tracking_report(*tracking_synthetic("grounded")))
    prior = object_tracking_gate(object_tracking_report(*tracking_synthetic("image_left")))
    assert grounded["pass"]
    assert not prior["pass"]
    assert any("right" in reason for reason in prior["reasons"])


def test_object_tracking_gate_rejects_a_side_with_too_few_scenes():
    preds, geom = tracking_synthetic("grounded", n=4)
    report = object_tracking_report(preds, geom)
    gate = object_tracking_gate(report, min_n_per_side=10)
    assert not gate["pass"]
    assert any("below the 10" in reason for reason in gate["reasons"])


def test_proportion_lower_bound_tracks_both_rate_and_cell_size():
    assert np.isnan(proportion_lower_bound(0, 0))
    # A perfect rate on two scenes is not demonstrably above chance.
    assert proportion_lower_bound(2, 2) < 0.5
    # The same rate on twenty scenes is.
    assert proportion_lower_bound(20, 20) > 0.5
    # The bound never exceeds the rate itself.
    assert proportion_lower_bound(120, 200) < 0.6


def test_object_tracking_gate_reads_bounds_not_point_rates():
    def report_with(n_toward, n_decided):
        side = {
            "n": n_decided,
            "n_decided_original": n_decided,
            "n_toward_original": n_toward,
        }
        return {
            "n": 2 * n_decided,
            "by_object_side": {OBJECT_SIDE_LEFT: dict(side),
                               OBJECT_SIDE_RIGHT: dict(side)},
        }

    # The same 60% rate fails on 20 decided scenes and passes on 200: the
    # criterion is the lower confidence bound, not the point rate.
    small = object_tracking_gate(report_with(12, 20), require_mirror=False)
    large = object_tracking_gate(report_with(120, 200), require_mirror=False)
    assert not small["pass"]
    assert large["pass"]


def test_object_tracking_report_is_empty_safe():
    empty = pd.DataFrame(columns=["scene_id", "condition", "c0", "a0"])
    assert object_tracking_report(empty, empty)["n"] == 0


def test_object_tracking_candidates_keep_single_object_validation_rows():
    from data import SPLIT_CONSTRUCTION, SPLIT_VALIDATION

    rows = [
        {"split": SPLIT_VALIDATION, "duplicate_target": "no",
         "instruction": "pick up the cup on the left"},
        {"split": SPLIT_VALIDATION, "duplicate_target": "yes",
         "instruction": "pick up the cup on the left"},
        {"split": SPLIT_CONSTRUCTION, "duplicate_target": "no",
         "instruction": "pick up the cup on the left"},
        {"split": SPLIT_VALIDATION, "duplicate_target": "no",
         "instruction": "put the cup on the shelf"},
    ]
    result = object_tracking_candidates(rows)
    assert result["n"] == 1
    kept = result["rows"][0]
    assert kept["noun"] == "cup"
    assert kept["instr_neutral"] == "pick up the cup"
    assert kept["spatial_term"] == "left"
    assert result["skipped"]["duplicate"] == 1
    assert result["skipped"]["split"] == 1
    assert result["skipped"]["pair"] == 1


def test_tracking_instruction_fixes_the_verb():
    from data import SPLIT_VALIDATION

    assert tracking_instruction("cup") == "pick up the cup"
    rows = [
        {"split": SPLIT_VALIDATION, "duplicate_target": "no",
         "instruction": "grab the mug on the right"},
    ]
    result = object_tracking_candidates(rows)
    assert result["n"] == 1
    assert result["rows"][0]["noun"] == "mug"
    assert result["rows"][0]["instr_neutral"] == "pick up the mug"


def test_apply_tracking_instruction_rewrites_stored_prompts():
    rows = [{"noun": "spoon", "instr_neutral": "grab the spoon"}]
    apply_tracking_instruction(rows)
    assert rows[0]["instr_neutral"] == "pick up the spoon"


def test_stale_tracking_prompt_count():
    rows = [
        {"noun": "cup", "instruction": "pick up the cup"},
        {"noun": "cup", "instruction": "grab the cup"},
        {"noun": "", "instruction": "pick up the cup"},
    ]
    assert stale_tracking_prompt_count(rows) == 1


def test_object_tracking_candidates_admit_unreviewed_and_unclear():
    """Detection, not the harvest label, decides that a scene holds one instance.

    `yes` is excluded because two instances make the term-free instruction
    ambiguous. Unreviewed and unclear rows still go to the detector.
    """
    from data import SPLIT_VALIDATION

    rows = [
        {"split": SPLIT_VALIDATION, "duplicate_target": "unreviewed",
         "instruction": "pick up the spoon on the right"},
        {"split": SPLIT_VALIDATION, "duplicate_target": "unclear",
         "instruction": "pick up the spoon on the right"},
    ]
    result = object_tracking_candidates(rows)
    assert result["n"] == 2
    assert result["skipped"]["duplicate"] == 0


def _grounded_pair(x_object, scale=0.01):
    side = np.sign(x_object - GRIPPER_X)
    orig = side * scale
    mirrored_side = np.sign(
        mirrored_x(x_object, FRAME_WIDTH) - mirrored_x(GRIPPER_X, FRAME_WIDTH))
    return orig, mirrored_side * scale


def test_object_tracking_report_reads_the_requested_axis():
    preds, geom = [], []
    for i in range(20):
        scene = f"t{i}"
        x_object = OBJECT_LEFT_X if i % 2 == 0 else OBJECT_RIGHT_X
        orig, mir = _grounded_pair(x_object)
        preds.append(_track_pred(scene, TRACKING_CONDITION_ORIGINAL, (0.0, orig, 0.0)))
        preds.append(_track_pred(scene, TRACKING_CONDITION_MIRROR, (0.0, mir, 0.0)))
        geom.append(_track_geom(scene, x_object))
    preds, geom = pd.DataFrame(preds), pd.DataFrame(geom)
    on_dx = object_tracking_report(preds, geom)
    on_dy = object_tracking_report(preds, geom, axis_index=1)
    assert on_dx["n_undecided_original"] == 20
    assert on_dy["flip_rate"] == pytest.approx(1.0)
    assert on_dy["toward_original"] == pytest.approx(1.0)
    assert on_dy["toward_mirror"] == pytest.approx(1.0)


def test_object_tracking_by_axis_separates_constant_dx_from_flipping_dy():
    preds, geom = [], []
    scale = 0.01
    for i in range(40):
        scene = f"t{i}"
        x_object = OBJECT_LEFT_X if i % 2 == 0 else OBJECT_RIGHT_X
        orig, mir = _grounded_pair(x_object, scale)
        preds.append(_track_pred(
            scene, TRACKING_CONDITION_ORIGINAL, (-scale, orig, 0.0)))
        preds.append(_track_pred(
            scene, TRACKING_CONDITION_MIRROR, (-scale, mir, 0.0)))
        geom.append(_track_geom(scene, x_object))
    preds, geom = pd.DataFrame(preds), pd.DataFrame(geom)
    scan = object_tracking_by_axis(preds, geom)
    dx, dy, dz = scan[0], scan[1], scan[2]
    assert dx["name"] == "dx"
    assert dx["flip_rate"] == pytest.approx(0.0)
    assert dx["negative_rate_original"] == pytest.approx(1.0)
    assert dx["by_object_side"][OBJECT_SIDE_LEFT]["toward_original"] == pytest.approx(1.0)
    assert dx["by_object_side"][OBJECT_SIDE_RIGHT]["toward_original"] == pytest.approx(0.0)
    assert not object_tracking_gate(dx)["pass"]
    assert dy["flip_rate"] == pytest.approx(1.0)
    assert dy["toward_original"] == pytest.approx(1.0)
    assert object_tracking_gate(dy)["pass"]
    assert dz["n_undecided_original"] == 40


def test_attach_tracking_ground_truth_joins_on_episode_index():
    geom = [{"scene_id": "b1", "episode_index": 7, "x_object": 1}]
    man = [{"episode_index": "7", "gt_dx": 0.1, "gt_dy": 0.2, "gt_dz": -0.3}]
    out = attach_tracking_ground_truth(geom, man)
    assert out.loc[0, "gt_dx"] == pytest.approx(0.1)
    assert out.loc[0, "gt_dz"] == pytest.approx(-0.3)


def test_tracking_gt_predictions_copies_gt_columns():
    geom = pd.DataFrame([{
        "scene_id": "b1", "gt_dx": 0.01, "gt_dy": 0.0, "gt_dz": -0.02,
    }, {
        "scene_id": "b2", "gt_dx": "", "gt_dy": "", "gt_dz": "",
    }])
    preds = tracking_gt_predictions(geom)
    assert len(preds) == 1
    assert preds.loc[0, "scene_id"] == "b1"
    assert list(preds["condition"]) == [TRACKING_CONDITION_ORIGINAL]
    assert preds.loc[0, "c0"] == pytest.approx(0.01)
    assert preds.loc[0, "c2"] == pytest.approx(-0.02)


def test_ground_truth_gate_scores_the_original_frame_only():
    preds, geom = tracking_synthetic("grounded")
    orig = preds[preds["condition"] == TRACKING_CONDITION_ORIGINAL]
    report = object_tracking_report(orig, geom, require_mirror=False)
    assert report["n"] == 40
    assert np.isnan(report["flip_rate"])
    gate = object_tracking_gate(report, require_mirror=False)
    assert gate["pass"]
    assert gate["require_mirror"] is False


def test_ground_truth_gate_rejects_a_constant_sign():
    preds, geom = tracking_synthetic("image_left")
    orig = preds[preds["condition"] == TRACKING_CONDITION_ORIGINAL]
    report = object_tracking_report(orig, geom, require_mirror=False)
    gate = object_tracking_gate(report, require_mirror=False, min_n_per_side=10)
    assert not gate["pass"]
    assert any("right" in reason and "toward" in reason for reason in gate["reasons"])
    assert not any("flip" in reason for reason in gate["reasons"])


def test_sign_scan_inverts_toward_object_on_the_original_frame():
    preds, geom = tracking_synthetic("grounded")
    orig = preds[preds["condition"] == TRACKING_CONDITION_ORIGINAL]
    scan = object_tracking_by_sign(
        orig, geom, axis_index=0, require_mirror=False, min_n_per_side=10)
    assert scan[1]["gate"]["pass"]
    assert not scan[-1]["gate"]["pass"]
    assert scan[-1]["report"]["toward_original"] == pytest.approx(
        1.0 - scan[1]["report"]["toward_original"])
