"""
tests/test_analysis.py: unit tests for the probe statistics in analysis.py.

The central test is that the battery discriminates the three accounts the study
must tell apart, using synthetic logs generated from each:

  * `grounded`: the action follows the scene, and the term selects which target.
  * `lexical`: the term fixes the direction and the image plays no part.
  * `blind`: the output ignores instruction and image alike.

A `lexical` model reproduces the antonym sign flip perfectly, so it passes the
original sign-flip metric. Confirming that the controls separate it from
`grounded` is what justifies the rebuild, and a regression there would silently
restore the ambiguity the earlier design suffered from.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from analysis import (
    absolute_congruence,
    axis_value,
    congruence_test,
    determinism_check,
    lexical_check,
    mirror_check,
    resolution_report,
    same_side_test,
    term_effect,
    tost_equivalence,
    value_column,
    wilcoxon_paired,
)

BIN_WIDTH = 0.001118


def _row(scene_id, condition, role, value, axis_index=0, configuration="opposite",
         expected_sign=-1, target_sign_a=-1, target_sign_b=1):
    row = {
        "scene_id": scene_id, "condition": condition, "role": role,
        "axis_index": axis_index, "configuration": configuration,
        "expected_sign": expected_sign,
        "target_sign_a": target_sign_a, "target_sign_b": target_sign_b,
        "instruction": f"{scene_id}-{role}-{condition}",
    }
    for i in range(7):
        row[f"c{i}"] = value if i == axis_index else 0.0
        row[f"a{i}"] = value if i == axis_index else 0.0
    return row


def synthetic_log(model, n=40, seed=0):
    """A prediction log generated by one of the three accounts."""
    rng = np.random.default_rng(seed)
    rows = []
    for s in range(n):
        configuration = "opposite" if s % 2 == 0 else "same_side_left"
        # Where each instruction's target sits, relative to the start position.
        # In the same-side arrangement both lie in the same direction, which is
        # the condition that separates the grounded and lexical accounts.
        if configuration == "opposite":
            target_a, target_b = -1.0, 1.0
        else:
            target_a, target_b = -1.0, -0.4
        scene = f"s{s}"

        def value(role, target, mirrored=False, no_referent=False):
            if model == "grounded":
                # The term-free instruction still reaches for the object, which
                # is the object-grounding baseline the mirror control reads.
                base = target_a if role == "n" else target
                if no_referent:
                    base = rng.choice([-1.0, 1.0]) * 0.05
                return -base if mirrored else base
            if model == "lexical":
                # The word fixes the direction; the scene plays no part, so
                # mirroring changes nothing.
                return {"a": -1.0, "b": 1.0, "n": 0.0}[role]
            return 0.0

        def row(condition, role, val):
            return _row(scene, condition, role, val * 0.01,
                        configuration=configuration,
                        expected_sign=int(np.sign(target_a - target_b)),
                        target_sign_a=int(np.sign(target_a)),
                        target_sign_b=int(np.sign(target_b)))

        for role, target in (("a", target_a), ("b", target_b)):
            rows.append(row("baseline", role, value(role, target)))
            rows.append(row("swapped_scene", role,
                            value(role, target, no_referent=True)))
        rows.append(row("neutral", "n", value("n", target_a)))
        rows.append(row("mirror", "a", value("a", target_a, mirrored=True)))
        rows.append(row("mirror_neutral", "n", value("n", target_a, mirrored=True)))
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------- #
# Axis selection
# --------------------------------------------------------------------------- #
def test_value_column_names_the_right_readout():
    assert value_column(0) == "c0" and value_column(1) == "c1"
    assert value_column(0, continuous=False) == "a0"


def test_axis_value_reads_each_row_on_its_own_axis():
    # Pooling a depth pair onto the lateral component is the bug this prevents.
    frame = pd.DataFrame([
        _row("lateral", "baseline", "a", 0.5, axis_index=0),
        _row("depth", "baseline", "a", 0.7, axis_index=1),
        _row("vertical", "baseline", "a", 0.9, axis_index=2),
    ])
    assert list(axis_value(frame)) == [0.5, 0.7, 0.9]


# --------------------------------------------------------------------------- #
# Paired tests
# --------------------------------------------------------------------------- #
def test_wilcoxon_reports_direction_and_size():
    result = wilcoxon_paired([0.1] * 10 + [0.05] * 10)
    assert result["n"] == 20
    assert result["median"] > 0
    assert result["p_value"] < 0.05
    assert result["rank_biserial"] == pytest.approx(1.0)


def test_wilcoxon_is_degenerate_safe():
    for values in ([], [0.0], [0.0] * 20):
        result = wilcoxon_paired(values)
        assert np.isnan(result["p_value"])
    assert wilcoxon_paired([0.0] * 20)["n_zero"] == 20


def test_wilcoxon_ignores_non_finite_values():
    assert wilcoxon_paired([0.1, np.nan, 0.2, np.inf])["n"] == 2


def test_tost_declares_a_tiny_effect_equivalent():
    rng = np.random.default_rng(0)
    tiny = rng.normal(0, BIN_WIDTH / 20, size=60)
    assert tost_equivalence(tiny, BIN_WIDTH)["equivalent"]


def test_tost_does_not_declare_a_large_effect_equivalent():
    rng = np.random.default_rng(0)
    large = rng.normal(10 * BIN_WIDTH, BIN_WIDTH, size=60)
    assert not tost_equivalence(large, BIN_WIDTH)["equivalent"]


def test_tost_handles_a_constant_sample():
    assert tost_equivalence([0.0] * 10, BIN_WIDTH)["equivalent"]
    assert not tost_equivalence([1.0] * 10, BIN_WIDTH)["equivalent"]


def test_tost_is_inconclusive_on_a_small_noisy_sample():
    # Neither different from zero nor demonstrably negligible.
    rng = np.random.default_rng(1)
    result = tost_equivalence(rng.normal(0, 5 * BIN_WIDTH, size=4), BIN_WIDTH)
    assert not result["equivalent"]


# --------------------------------------------------------------------------- #
# Resolution
# --------------------------------------------------------------------------- #
def test_resolution_report_exposes_a_floored_measurement():
    result = resolution_report([0.0] * 30, BIN_WIDTH)
    assert result["frac_exact_zero"] == 1.0
    assert result["n_distinct"] == 1


def test_resolution_report_counts_sub_bin_differences():
    values = [BIN_WIDTH / 4] * 10 + [BIN_WIDTH * 5] * 10
    result = resolution_report(values, BIN_WIDTH)
    assert result["frac_below_bin"] == pytest.approx(0.5)
    assert result["frac_exact_zero"] == 0.0


def test_resolution_report_handles_empty_input():
    assert resolution_report([], BIN_WIDTH)["n"] == 0


# --------------------------------------------------------------------------- #
# Discrimination between the three accounts
# --------------------------------------------------------------------------- #
def test_mirror_check_separates_a_live_visual_channel_from_a_dead_one():
    grounded = mirror_check(synthetic_log("grounded"))
    lexical = mirror_check(synthetic_log("lexical"))
    assert grounded["neutral"]["flip_rate"] == pytest.approx(1.0)
    assert grounded["neutral"]["antisymmetry"]["median"] == pytest.approx(0.0)
    # The lexical model's output does not move when the scene is reflected.
    assert lexical["term"]["flip_rate"] == pytest.approx(0.0)
    assert lexical["term"]["invariance"]["median"] == pytest.approx(0.0)


def test_lexical_check_detects_a_contrast_that_survives_without_its_scene():
    grounded = lexical_check(synthetic_log("grounded"))
    lexical = lexical_check(synthetic_log("lexical"))
    assert grounded["ratio"] < 0.2
    assert lexical["ratio"] == pytest.approx(1.0)


def test_same_side_test_is_the_decisive_contrast():
    grounded = same_side_test(synthetic_log("grounded"))
    lexical = same_side_test(synthetic_log("lexical"))
    # Both accounts behave identically on the opposite configuration, which is
    # exactly why that arrangement alone cannot decide between them.
    assert grounded["by_configuration"]["opposite"]["same_sign_rate"] == pytest.approx(0.0)
    assert lexical["by_configuration"]["opposite"]["same_sign_rate"] == pytest.approx(0.0)
    # They diverge completely on the same-side configuration.
    assert grounded["by_configuration"]["same_side_left"]["same_sign_rate"] == pytest.approx(1.0)
    assert lexical["by_configuration"]["same_side_left"]["same_sign_rate"] == pytest.approx(0.0)
    assert grounded["contrast"]["difference"] == pytest.approx(1.0)
    assert grounded["contrast"]["p_value"] < 0.01
    assert lexical["contrast"]["difference"] == pytest.approx(0.0)


def test_congruence_on_the_difference_cannot_separate_the_accounts():
    # Both accounts orient the paired difference the same way, because the
    # term's conventional direction and the recorded order of the two targets
    # coincide by construction. This is the limitation that makes the paired
    # difference, and the original sign-flip metric built on it, insufficient
    # on its own; absolute_congruence is the statistic that discriminates.
    assert congruence_test(synthetic_log("grounded"))["agreement"] == pytest.approx(1.0)
    assert congruence_test(synthetic_log("lexical"))["agreement"] == pytest.approx(1.0)


def test_absolute_congruence_separates_the_accounts_on_same_side_scenes():
    grounded = absolute_congruence(synthetic_log("grounded"))["by_configuration"]
    lexical = absolute_congruence(synthetic_log("lexical"))["by_configuration"]
    # Both targets share a side, so a fixed word-to-direction mapping can only
    # ever point at one of them.
    assert grounded["same_side_left"]["agreement"] == pytest.approx(1.0)
    assert lexical["same_side_left"]["agreement"] == pytest.approx(0.5)
    assert grounded["same_side_left"]["both_correct"] == pytest.approx(1.0)
    assert lexical["same_side_left"]["both_correct"] == pytest.approx(0.0)
    # The opposite arrangement cannot tell them apart, which is why the rate is
    # reported per configuration rather than pooled.
    assert grounded["opposite"]["agreement"] == pytest.approx(1.0)
    assert lexical["opposite"]["agreement"] == pytest.approx(1.0)


def test_absolute_congruence_reports_when_the_target_sides_were_not_logged():
    log = synthetic_log("grounded").drop(columns=["target_sign_a", "target_sign_b"])
    assert absolute_congruence(log)["n"] == 0


def test_term_effect_finds_opposed_deviations_only_where_the_term_acts():
    lexical = term_effect(synthetic_log("lexical"))
    blind = term_effect(synthetic_log("blind"))
    assert lexical["opposed_rate"] == pytest.approx(1.0)
    assert blind["both_zero_rate"] == pytest.approx(1.0)


def test_a_blind_model_produces_a_null_everywhere():
    log = synthetic_log("blind")
    assert same_side_test(log)["by_configuration"]["opposite"]["n"] == 0
    assert term_effect(log)["opposed_rate"] == pytest.approx(0.0)
    diffs = np.zeros(20)
    assert tost_equivalence(diffs, BIN_WIDTH)["equivalent"]


def test_statistics_are_empty_safe():
    empty = pd.DataFrame(columns=["scene_id", "condition", "role", "axis_index",
                                  "configuration", "expected_sign", "instruction",
                                  "target_sign_a", "target_sign_b",
                                  *[f"c{i}" for i in range(7)],
                                  *[f"a{i}" for i in range(7)]])
    assert mirror_check(empty)["term"]["n"] == 0
    assert term_effect(empty)["n"] == 0
    assert congruence_test(empty)["n"] == 0
    assert same_side_test(empty)["n"] == 0
    assert absolute_congruence(empty)["n"] == 0
    assert determinism_check(empty)["deterministic"]


# --------------------------------------------------------------------------- #
# Determinism
# --------------------------------------------------------------------------- #
def test_determinism_check_passes_on_identical_repeats():
    log = synthetic_log("grounded", n=5)
    doubled = pd.concat([log, log], ignore_index=True)
    assert determinism_check(doubled)["deterministic"]


def test_determinism_check_catches_a_disagreeing_repeat():
    log = synthetic_log("grounded", n=5)
    drifted = log.copy()
    drifted.loc[drifted.index[0], "c0"] += 1e-6
    doubled = pd.concat([log, drifted], ignore_index=True)
    result = determinism_check(doubled)
    assert not result["deterministic"]
    assert result["max_spread"] > 0
